import React, { useEffect, useState } from 'react';
import AppLayout from '../components/layout/AppLayout';
import { recommendationService } from '../services/api';
import { LoadingState, ErrorState } from '../components/ui/Shared';
import { Lightbulb, ChevronRight } from 'lucide-react';

const PRIORITY_STYLES = {
  URGENT: 'bg-red-500/20 text-red-400 border border-red-500/40',
  HIGH: 'bg-orange-500/20 text-orange-400 border border-orange-500/40',
  MEDIUM: 'bg-amber-500/20 text-amber-400 border border-amber-500/40',
  LOW: 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/40',
};

const TYPE_ICONS = {
  COST: '💰',
  SCHEDULE: '📅',
  PROGRESS: '📈',
  FINANCE: '💳',
  PROCUREMENT: '📦',
};

export default function RecommendationsPage() {
  const [recs, setRecs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [filter, setFilter] = useState('ALL');

  useEffect(() => {
    recommendationService.getAll()
      .then(r => setRecs(r.data || []))
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  const filtered = filter === 'ALL' ? recs : recs.filter(r => r.priorityLevel === filter);

  if (loading) return <AppLayout><LoadingState /></AppLayout>;
  if (error) return <AppLayout><ErrorState message={error} /></AppLayout>;

  return (
    <AppLayout>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-100 flex items-center gap-3">
          <Lightbulb className="w-6 h-6 text-amber-400" />
          AI Recommendations
        </h1>
        <p className="text-slate-400 text-sm mt-1">
          System-generated suggested actions based on risk analysis — not guaranteed outcomes
        </p>
      </div>

      <div className="bg-amber-500/5 border border-amber-500/20 rounded-xl p-4 mb-6 text-sm text-amber-300">
        <strong>Note:</strong> These are <em>suggested actions</em> and <em>potential interventions</em> generated by the AI system.
        They are not guaranteed solutions. All recommendations should be reviewed by qualified domain experts before action.
      </div>

      {/* Filter */}
      <div className="flex gap-2 mb-6 flex-wrap">
        {['ALL', 'URGENT', 'HIGH', 'MEDIUM', 'LOW'].map(f => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors ${filter === f
              ? 'bg-cyan-500/20 border border-cyan-500/40 text-cyan-400'
              : 'bg-slate-800 border border-slate-700 text-slate-400 hover:text-slate-200'}`}
          >
            {f} {filter !== f && `(${recs.filter(r => f === 'ALL' || r.priorityLevel === f).length})`}
          </button>
        ))}
      </div>

      {/* Recommendation cards */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
        {filtered.length === 0 && (
          <div className="col-span-2 text-center py-16 text-slate-500">No recommendations found</div>
        )}
        {filtered.map((r) => (
          <div key={r.id} className="bg-slate-900/70 border border-slate-800 hover:border-slate-700 rounded-xl p-5 transition-colors animate-slide-in">
            <div className="flex items-start justify-between gap-3 mb-3">
              <div className="flex items-center gap-2">
                <span className="text-xl">{TYPE_ICONS[r.recommendationType] || '🔍'}</span>
                <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold uppercase ${PRIORITY_STYLES[r.priorityLevel]}`}>
                  {r.priorityLevel}
                </span>
                {r.recommendationType && (
                  <span className="text-xs text-slate-500 bg-slate-800 px-2 py-0.5 rounded">{r.recommendationType}</span>
                )}
              </div>
              <span className="text-xs text-slate-500 shrink-0">Project #{r.projectId}</span>
            </div>

            <h3 className="font-semibold text-slate-200 mb-2">{r.title}</h3>
            <p className="text-sm text-slate-400 leading-relaxed">{r.description}</p>

            <div className="mt-4 flex items-center gap-2 text-xs text-slate-500">
              <ChevronRight className="w-3.5 h-3.5 text-amber-400" />
              <span className="text-amber-300">Review recommended — potential intervention identified</span>
            </div>
          </div>
        ))}
      </div>
    </AppLayout>
  );
}
