import React, { useEffect, useState } from 'react';
import AppLayout from '../components/layout/AppLayout';
import { recommendationService } from '../services/api';
import { LoadingState, ErrorState } from '../components/ui/Shared';
import { Lightbulb, ChevronRight, CheckCircle2 } from 'lucide-react';

const PRIORITY_STYLES = {
  URGENT: 'bg-red-50 text-red-700 border border-red-200',
  HIGH: 'bg-orange-50 text-orange-700 border border-orange-200',
  MEDIUM: 'bg-amber-50 text-amber-700 border border-amber-200',
  LOW: 'bg-emerald-50 text-emerald-700 border border-emerald-200',
};

const TYPE_ICONS = {
  COST: '💰',
  SCHEDULE: '📅',
  PROGRESS: '📈',
  FINANCE: '💳',
  PROCUREMENT: '📦',
};

export default function RecommendationsPage() {
  const [recs, setRecs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [filter, setFilter] = useState('ALL');

  useEffect(() => {
    recommendationService.getAll()
      .then(r => setRecs(r.data || []))
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  const filtered = filter === 'ALL' ? recs : recs.filter(r => r.priorityLevel === filter);

  if (loading) return <AppLayout><LoadingState /></AppLayout>;
  if (error) return <AppLayout><ErrorState message={error} /></AppLayout>;

  return (
    <AppLayout>
      <div className="mb-6">
        <div className="text-xs font-semibold text-slate-500 mb-1 tracking-wide uppercase">Home / Recommendations</div>
        <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
          <Lightbulb className="w-6 h-6 text-brand-600" />
          AI Recommendations
        </h1>
        <p className="text-slate-600 text-sm mt-1">
          System-generated suggested actions based on risk analysis — review before action
        </p>
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded p-4 mb-6 text-sm text-amber-800 flex items-start gap-3">
        <Lightbulb className="w-5 h-5 text-amber-600 mt-0.5 shrink-0" />
        <div>
          <strong className="block mb-1">Important Notice:</strong> 
          These are <em>suggested actions</em> and <em>potential interventions</em> generated by the AI system. They are not guaranteed solutions. All recommendations should be reviewed by qualified domain experts before execution.
        </div>
      </div>

      {/* Filter */}
      <div className="gov-card p-4 mb-6 flex flex-wrap gap-2">
        <span className="text-sm font-semibold text-slate-700 mt-1.5 mr-2">Filter by Priority:</span>
        {['ALL', 'URGENT', 'HIGH', 'MEDIUM', 'LOW'].map(f => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-4 py-1.5 rounded text-sm font-semibold transition-colors border ${filter === f
              ? 'bg-brand-50 border-brand-300 text-brand-700'
              : 'bg-white border-slate-300 text-slate-600 hover:bg-slate-50'}`}
          >
            {f} {filter !== f && <span className="opacity-70 font-normal">({recs.filter(r => f === 'ALL' || r.priorityLevel === f).length})</span>}
          </button>
        ))}
      </div>

      {/* Recommendation cards */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-5">
        {filtered.length === 0 && (
          <div className="col-span-1 xl:col-span-2 gov-card text-center py-16 text-slate-500 font-medium">No recommendations found</div>
        )}
        {filtered.map((r) => (
          <div key={r.id} className="gov-card p-6 flex flex-col justify-between hover:border-brand-200 transition-colors">
            <div>
              <div className="flex items-start justify-between gap-3 mb-4">
                <div className="flex items-center gap-3">
                  <span className="text-2xl bg-slate-50 p-2 rounded border border-slate-100">{TYPE_ICONS[r.recommendationType] || '🔍'}</span>
                  <div>
                    <span className={`text-[10px] px-2 py-0.5 rounded font-bold uppercase ${PRIORITY_STYLES[r.priorityLevel]}`}>
                      {r.priorityLevel}
                    </span>
                    {r.recommendationType && (
                      <span className="block mt-1 text-xs font-bold text-slate-500 uppercase tracking-wide">{r.recommendationType}</span>
                    )}
                  </div>
                </div>
                <span className="text-xs font-bold text-slate-500 bg-slate-100 px-2 py-1 rounded shrink-0">Project #{r.projectId}</span>
              </div>

              <h3 className="font-bold text-slate-900 text-lg mb-2">{r.title}</h3>
              <p className="text-sm font-medium text-slate-600 leading-relaxed mb-4">{r.description}</p>
            </div>

            <div className="pt-4 border-t border-slate-100 flex items-center gap-2 text-xs font-semibold text-slate-600">
              <CheckCircle2 className="w-4 h-4 text-brand-600" />
              <span>Review recommended — potential intervention identified</span>
            </div>
          </div>
        ))}
      </div>
    </AppLayout>
  );
}
