import React from 'react';
import { Link } from 'react-router-dom';
import { Activity, Database, Brain, Bell, GitBranch, ShieldCheck, Scale, ArrowRight } from 'lucide-react';

const LIFECYCLE = [
  {
    code: 'MONITOR',
    title: 'Monitor',
    body: 'Project master data and monthly progress snapshots are captured through the authenticated dashboard or imported from CSV. Every upload is validated row by row before anything is written.',
    icon: Database,
  },
  {
    code: 'ANALYZE',
    title: 'Analyze',
    body: 'Threshold rules compare physical and financial progress, cost escalation, milestone slippage and fund utilisation against configurable limits, and raise alerts with a suggested action.',
    icon: Activity,
  },
  {
    code: 'PREDICT',
    title: 'Predict',
    body: 'Three models score each project: cost overrun probability, schedule overrun probability, and an overall risk score. The Spring Boot service calls the Python model service and persists the result with the model version that produced it.',
    icon: Brain,
  },
  {
    code: 'EXPLAIN',
    title: 'Explain',
    body: 'Every prediction is decomposed with SHAP into per-feature contributions, so an analyst can see which inputs drove a score instead of taking the number on trust.',
    icon: GitBranch,
  },
  {
    code: 'RECOMMEND',
    title: 'Recommend',
    body: 'Rules and model signals are combined into prioritised recommendations, and officers record whether each one was actioned, so the portal tracks follow-through as well as detection.',
    icon: Scale,
  },
  {
    code: 'ALERT',
    title: 'Alert',
    body: 'Resolved findings, model-driven risk changes and data-quality problems are surfaced on a single dashboard, with severity and acknowledgement state.',
    icon: Bell,
  },
];

const DATA_SOURCES = [
  {
    name: 'Cost overrun dataset (Kaggle)',
    status: 'Real observations',
    detail:
      'The public "Project Overrun Prediction" dataset supplies budget, material, labour, equipment and expenditure figures. It is the basis for the cost model.',
  },
  {
    name: 'Schedule and overall-risk labels',
    status: 'Seeded synthetic',
    detail:
      'The cost dataset contains no schedule, milestone or completion-date ground truth, so schedule-slip and risk labels are generated by a fixed-seed script. The pipeline is genuine; the labels are not.',
  },
  {
    name: 'Project master and progress data',
    status: 'Operational',
    detail:
      'Entered through the portal or bulk-imported as CSV, with per-row validation, dry-run previews and upsert semantics on the project code and reporting month.',
  },
];

const COMPONENTS = [
  { name: 'React + Vite', role: 'Public portal and authenticated dashboard' },
  { name: 'Spring Boot 3', role: 'REST API, security, rules engine, scheduled jobs' },
  { name: 'FastAPI', role: 'Model training, serving, SHAP explainability' },
  { name: 'MySQL', role: 'System of record for projects, predictions and alerts' },
];

const ROLES = [
  { role: 'Viewer', can: 'Read public pages, dashboards, alerts and recommendations' },
  { role: 'Analyst', can: 'Everything a viewer can, plus risk analytics and model performance' },
  { role: 'Monitor', can: 'Import monthly data, run predictions, resolve alerts, record actions' },
  { role: 'Project manager', can: 'Create and edit projects' },
  { role: 'Administrator', can: 'Manage users and the project master; import full datasets' },
];

export default function AboutPage() {
  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
      <header>
        <p className="text-xs font-semibold text-brand-600 uppercase tracking-widest">About</p>
        <h1 className="text-3xl font-bold text-slate-900 mt-2">InfraWatch AI</h1>
        <p className="text-slate-600 mt-3 leading-relaxed">
          An early-warning system for public infrastructure projects. It tracks progress against sanctioned cost
          and schedule, scores the risk that a project will overrun on either axis, explains what drove that score,
          and records what was done about it.
        </p>
      </header>

      <section>
        <h2 className="text-xl font-bold text-slate-900 mb-1">How the platform works</h2>
        <p className="text-slate-600 text-sm mb-5">
          Each project moves through six stages. The stages are not separate products — a single prediction flows
          from monitoring data, through the rules engine and the models, into an explained, attributed and
          acknowledged recommendation.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {LIFECYCLE.map(({ code, title, body, icon: Icon }, index) => (
            <div key={code} className="bg-white border border-slate-200 rounded-lg p-5 shadow-sm">
              <div className="flex items-center justify-between mb-3">
                <div className="bg-brand-50 p-2 rounded-lg">
                  <Icon className="w-5 h-5 text-brand-600" />
                </div>
                <span className="text-[10px] font-bold text-slate-400 tracking-widest">{code}</span>
              </div>
              <h3 className="font-bold text-slate-800 mb-1.5">
                <span className="text-slate-400 mr-1.5">{index + 1}.</span>
                {title}
              </h3>
              <p className="text-sm text-slate-600 leading-relaxed">{body}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="bg-amber-50 border border-amber-200 rounded-lg p-6">
        <h2 className="text-lg font-bold text-amber-900 mb-2 flex items-center gap-2">
          <ShieldCheck className="w-5 h-5" /> What the numbers do and do not mean
        </h2>
        <div className="space-y-3">
          {DATA_SOURCES.map((source) => (
            <div key={source.name}>
              <div className="flex flex-wrap items-center gap-2">
                <span className="font-semibold text-amber-900 text-sm">{source.name}</span>
                <span
                  className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase tracking-wide ${
                    source.status === 'Real observations'
                      ? 'bg-emerald-100 text-emerald-800'
                      : source.status === 'Seeded synthetic'
                        ? 'bg-amber-200 text-amber-900'
                        : 'bg-slate-200 text-slate-700'
                  }`}
                >
                  {source.status}
                </span>
              </div>
              <p className="text-sm text-amber-900/80 mt-1 leading-relaxed">{source.detail}</p>
            </div>
          ))}
        </div>
        <p className="text-sm text-amber-900/90 mt-4 pt-4 border-t border-amber-300 leading-relaxed">
          Cost-overrun scores are trained on real historical data. Schedule-slip and overall-risk scores are trained
          on generated labels, so their accuracy figures describe fit to that generated data and{' '}
          <strong>must not</strong> be read as evidence about any real project. Every prediction page carries this
          warning, and the Model Performance screen labels each target's provenance.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-bold text-slate-900 mb-4">System components</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {COMPONENTS.map((c) => (
            <div key={c.name} className="bg-white border border-slate-200 rounded-lg px-4 py-3">
              <p className="font-semibold text-slate-800 text-sm">{c.name}</p>
              <p className="text-slate-600 text-sm">{c.role}</p>
            </div>
          ))}
        </div>
      </section>

      <section>
        <h2 className="text-xl font-bold text-slate-900 mb-4">Access model</h2>
        <div className="bg-white border border-slate-200 rounded-lg overflow-hidden">
          <table className="w-full text-sm text-left">
            <thead className="bg-slate-50 border-b border-slate-200">
              <tr>
                <th className="px-4 py-3 font-bold text-slate-600 uppercase text-xs tracking-wide">Role</th>
                <th className="px-4 py-3 font-bold text-slate-600 uppercase text-xs tracking-wide">Capabilities</th>
              </tr>
            </thead>
            <tbody>
              {ROLES.map((r) => (
                <tr key={r.role} className="border-b border-slate-100 last:border-0">
                  <td className="px-4 py-3 font-semibold text-slate-800 whitespace-nowrap">{r.role}</td>
                  <td className="px-4 py-3 text-slate-600">{r.can}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="text-sm text-slate-500 mt-3">
          Accounts are provisioned by an administrator. Self-registration, where enabled, can only grant viewer,
          analyst or monitor — never an administrative or project-manager role.
        </p>
      </section>

      <section className="flex flex-wrap gap-3 pt-2">
        <Link
          to="/projects"
          className="inline-flex items-center gap-2 bg-brand-600 hover:bg-brand-700 text-white px-5 py-2.5 rounded-md text-sm font-semibold transition-colors"
        >
          Browse the project directory <ArrowRight className="w-4 h-4" />
        </Link>
        <Link
          to="/reports"
          className="inline-flex items-center gap-2 bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 px-5 py-2.5 rounded-md text-sm font-semibold transition-colors"
        >
          View the monitoring report
        </Link>
      </section>
    </div>
  );
}
